# Generated by Django 5.0.6 on 2024-06-05 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='comuna',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='direccion',
        ),
    ]
